name: CI - Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:8080/index.html

      - name: Run Cypress tests
        run: npm run test