name: CI/CD Cypress Tests

on:
  push:
    branches:
      - master  # ou main
  pull_request:
    branches:
      - master  # ou main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # recommandé pour éviter les warnings

      - name: Install dependencies
        run: npm install

      # Étape pour mettre en cache le binaire Cypress
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Fixer les permissions des binaires dans node_modules/.bin
      - name: Fix permissions for node_modules/.bin
        run: chmod +x $PWD/node_modules/.bin/*

      # Ajouter cette étape pour que les binaires locaux soient trouvés
      - name: Ajouter node_modules/.bin au PATH
        run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH

      # Lancer le serveur
      - name: Start local server
        run: serve -s . -l 8080 &

      # Attendre que le serveur soit prêt
      - name: Wait for server
        run: wait-on http://localhost:8080

      # Installer Cypress si le binaire est manquant
      - name: Install Cypress binary
        run: npx cypress install

      # Lancer les tests Cypress
      - name: Run Cypress Tests
        run: npm run test
        env:
          CYPRESS_baseUrl: http://localhost:8080